build-image:
    tags:
        - docker
    script:
        - ""
    variables:
        TO: $CI_REGISTRY_IMAGE/static:latest
        DOCKER_FILE: Dockerfile
    only:
        - main

stages:
  - build

# Build and push the Docker image to the GitLab image
# registry using Docker-in-Docker.
dind-build:
  stage: build

  image:
    name: docker:stable

  services:
   - name: docker:dind
     alias: dockerdaemon

  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"